Repository DACOS-SOLUX-Hackathon-Team5/Alddeul_Babsang-Android, pull requests merged in 2024-11, with the labels that each got.

#3 [DOCS#1] : Android CI 구축
  .github/workflows/pull_request_ci.yml
Labels: :rabbit: 가을, :scroll: [DOCS]

#7 [Feature/#6] : 리뷰 작성하기 페이지 구현
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/component/AlddeulButton.kt
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/component/AlddeulTextField.kt
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/theme/Color.kt
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/theme/Type.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/navigation/DetailNavGraph.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/navigation/DetailNavigator.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/ReviewScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/navigator/AlddeulNavHost.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/drawable/ic_review_star.xml
  app/src/main/res/values/strings.xml
Labels: :rabbit: 가을, :art: [UI]

#14 [Feature/#13] : 스플래시&로그인&회원가입2 페이지 구현
  app/src/main/AndroidManifest.xml
  app/src/main/ic_alddeul_logo-playstore.png
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/component/AlddeulButton.kt
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/component/AuthTextField.kt
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/theme/Color.kt
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/theme/Type.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/gitkeep
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/navigation/AuthNavGraph.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/navigation/AuthNavigator.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/screen/SignUp1Screen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/screen/SignUp2Screen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/screen/SplashScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/ReviewScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/main/screen/MainActivity.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/map/screen/MapScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/navigator/AlddeulNavHost.kt
  app/src/main/res/drawable/ic_alddeul_logo_background.xml
  app/src/main/res/drawable/ic_login_logo.png
  app/src/main/res/drawable/ic_signup_camera.xml
  app/src/main/res/drawable/ic_signup_profile.png
  app/src/main/res/drawable/ic_splash_logo.png
  app/src/main/res/font/bm_dohyeon.otf
  app/src/main/res/mipmap-anydpi-v26/ic_alddeul_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_alddeul_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_alddeul_logo.webp
  app/src/main/res/mipmap-hdpi/ic_alddeul_logo_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_alddeul_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_alddeul_logo.webp
  app/src/main/res/mipmap-mdpi/ic_alddeul_logo_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_alddeul_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_alddeul_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_alddeul_logo_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_alddeul_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_alddeul_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_alddeul_logo_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_alddeul_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_alddeul_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_alddeul_logo_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_alddeul_logo_round.webp
  app/src/main/res/values/strings.xml
Labels: :rabbit: 가을, :art: [UI]

#15 [Feature/#11] 프로필 페이지 & 좋아요 목록 페이지 구현
  app/src/main/java/com/hackathon/alddeul_babsang/domain/entity/BabsangListEntity.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/navigation/ProfileNavGraph.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/navigation/ProfileNavigator.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/BabsangListItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/BabsangListViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/ProfileLikeListScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/ProfileScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/ProfileScreenItem.kt
  app/src/main/res/values/strings.xml
Labels: :cat: 서연, :art: [UI]

#19 [Feature/#17] : 좋아요 페이지 리팩토링
  app/src/main/java/com/hackathon/alddeul_babsang/app/Qualifier.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/DataSourceModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/Extension.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/Qualifier.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/RepositoryModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/RetrofitModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/ServiceModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/UserPreferencesModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/interceptor/TokenInterceptor.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasource/UserPreferencesDataSource.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasourceimpl/UserPreferencesDataSourceImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/repositoryimpl/UserPreferencesRepositoryImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/entity/BabsangDetailEntity.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/entity/LikesEntity.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/repository/UserPreferencesRepository.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/screen/LoginScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/screen/LoginViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/auth/screen/SplashScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/ReviewItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/navigation/ProfileNavGraph.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/navigation/ProfileNavigator.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/LikeItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/LikeScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/LikeViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/ProfileItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/ProfileScreen.kt
  app/src/main/res/drawable/ic_right_arrow.xml
  app/src/main/res/values/strings.xml
Labels: :rabbit: 가을, :recycle: [REFACTOR]

#18 [Feature/#16] 착한 밥상 & 예비 착한 밥상 페이지 구현
  app/src/main/java/com/hackathon/alddeul_babsang/domain/entity/BabsangRecommendEntity.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/navigation/BabsangNavigator.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangListItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangRecommendItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangRecommendViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/report/navigation/ReportNavigator.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/report/screen/ReportBabsangListItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/report/screen/ReportBabsangViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/report/screen/ReportScreen.kt
  app/src/main/res/values/strings.xml
Labels: :cat: 서연, :art: [UI]

#22 [Feature/#21] : 상세 페이지 추천 식당 UI 구현
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/navigation/DetailNavigator.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailRecommendedItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailViewModel.kt
  app/src/main/res/values/strings.xml
Labels: :rabbit: 가을, :white_check_mark: [MOD], :art: [UI]

#24 [Feature/#23] : api 기초세팅
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/BaseResponse.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/ApiKeyStorage.kt
Labels: :rabbit: 가을, :star: [FEAT]

#27 [Feature/#23] : 착한 밥상 조회 api 연결
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/DataSourceModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/RepositoryModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/ServiceModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/core_ui/component/LoadingCircleIndicator.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasource/BabsangDataSource.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasourceimpl/BabsangDataSourceImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/response/ResponseBabsangDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/repositoryimpl/BabsangRepositoryImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/BabsangApiService.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/repository/BabsangRepository.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangViewModel.kt
Labels: :rabbit: 가을, :star: [FEAT]

#29 [Feature/#28] : 좋아요, 리뷰, 제보, 착한 업소 api 연결
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/DataSourceModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/RepositoryModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/ServiceModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasource/DetailDataSource.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasource/ProfileDataSource.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasourceimpl/DetailDataSourceImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasourceimpl/ProfileDataSourceImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/request/RequestLikesDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/request/gitkeep
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/response/ResponseLikesDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/response/ResponseReviewDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/repositoryimpl/DetailRepositoryImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/repositoryimpl/ProfileRepositoryImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/ApiKeyStorage.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/DetailApiService.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/ProfileApiService.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/repository/DetailRepository.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/repository/ProfileRepository.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/babsang/screen/BabsangItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/ReviewScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/ReviewViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/LikeItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/LikeScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/profile/screen/LikeViewModel.kt
Labels: :rabbit: 가을, :star: [FEAT]

#31 [Feature/#30] : 지도 api 연결
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/DataSourceModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/RepositoryModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/ServiceModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasource/MapDataSource.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasourceimpl/MapDataSourceImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/response/ResponseMapStoreDetailDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/response/ResponseMapStoresDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/ApiKeyStorage.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/MapApiService.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/repository/MapRepository.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/map/screen/MapScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/map/screen/MapViewModel.kt
Labels: :rabbit: 가을, :star: [FEAT]

#33 [Feautre/#32] : 리뷰 api 연결
  app/src/main/java/com/hackathon/alddeul_babsang/app/di/RetrofitModule.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasource/DetailDataSource.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasource/MapDataSource.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasourceimpl/DetailDataSourceImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/datasourceimpl/MapDataSourceImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/request/RequestMapStoreDetailDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/response/ResponseGetReviewDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/dto/response/ResponseMapStoreDetailDto.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/repositoryimpl/DetailRepositoryImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/repositoryimpl/MapRepositoryImpl.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/ApiKeyStorage.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/DetailApiService.kt
  app/src/main/java/com/hackathon/alddeul_babsang/data/service/MapApiService.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/repository/DetailRepository.kt
  app/src/main/java/com/hackathon/alddeul_babsang/domain/repository/MapRepository.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/DetailViewModel.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/detail/screen/ReviewItem.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/map/screen/MapScreen.kt
  app/src/main/java/com/hackathon/alddeul_babsang/presentation/map/screen/MapViewModel.kt
Labels: :rabbit: 가을, :star: [FEAT]
